### ISSUE TITLE
Grafica

### ISSUE THREAD

**Issue by speletti** [msambusiti/Crono#3]
La grafica è poco piacevole alla vista

**Comment by msambusiti** [comment]
Ci lavore-romolo....

**Comment by speletti** [comment]
Quando parte il conteggio si perde lo zero filling
Pressioni ripetute dell'avvia mandano a pallino tutto
Non c'è limitazione ai numeri inseriti
Non c'è emissionedi messaggi di errore che guidino l'utenza

**Comment by speletti** [comment]
> 
> 
> Ci lavore-romolo....

.....................
